// Generated by scripts/gen-cockpit-contracts.mjs — do not edit.
// Run `npm run docs:gen-openapi` in the repository root after changing a
// closed set on the server. test/unit/docs-drift.test.mjs guards this file.

/** content kind, from the OpenAPI document. */
export const CONTENT_KIND = [
  'page',
  'post',
  'project',
  'deck',
] as const
export type ContentKind = (typeof CONTENT_KIND)[number]

/** revision status, from the OpenAPI document. */
export const REVISION_STATUS = [
  'draft',
  'scheduled',
  'published',
  'archived',
] as const
export type RevisionStatus = (typeof REVISION_STATUS)[number]

/** comment status, from the OpenAPI document. */
export const COMMENT_STATUS = [
  'pending',
  'approved',
  'rejected',
] as const
export type CommentStatus = (typeof COMMENT_STATUS)[number]

/** contact status, from the OpenAPI document. */
export const CONTACT_STATUS = [
  'new',
  'read',
  'closed',
] as const
export type ContactStatus = (typeof CONTACT_STATUS)[number]

/** webhook delivery status, from the OpenAPI document. */
export const WEBHOOK_DELIVERY_STATUS = [
  'pending',
  'delivered',
  'failed',
] as const
export type WebhookDeliveryStatus = (typeof WEBHOOK_DELIVERY_STATUS)[number]

/** audio job status, from the OpenAPI document. */
export const AUDIO_JOB_STATUS = [
  'pending',
  'processing',
  'done',
  'failed',
  'skipped',
] as const
export type AudioJobStatus = (typeof AUDIO_JOB_STATUS)[number]

/** access rule match, from the OpenAPI document. */
export const ACCESS_RULE_MATCH = [
  'exact',
  'prefix',
] as const
export type AccessRuleMatch = (typeof ACCESS_RULE_MATCH)[number]

/** operator role, from the OpenAPI document. */
export const OPERATOR_ROLE = [
  'admin',
  'author',
  'reader',
] as const
export type OperatorRole = (typeof OPERATOR_ROLE)[number]

/** presentation preset, from the OpenAPI document. */
export const PRESENTATION_PRESET = [
  'portfolio',
  'product-docs',
  'wiki',
  'knowledge-base',
  'product',
  'changelog',
] as const
export type PresentationPreset = (typeof PRESENTATION_PRESET)[number]

/** report cadence, from the OpenAPI document. */
export const REPORT_CADENCE = [
  'hourly',
  'daily',
  'weekly',
  'monthly',
  'quarterly',
  'yearly',
] as const
export type ReportCadence = (typeof REPORT_CADENCE)[number]

/** render scheme, from the OpenAPI document. */
export const RENDER_SCHEME = [
  'auto',
  'light',
  'dark',
] as const
export type RenderScheme = (typeof RENDER_SCHEME)[number]

/** stats bucket, from the OpenAPI document. */
export const STATS_BUCKET = [
  'hour',
  'day',
  'month',
  'year',
] as const
export type StatsBucket = (typeof STATS_BUCKET)[number]

/** traffic class, from the OpenAPI document. */
export const TRAFFIC_CLASS = [
  'organic',
  'synthetic',
  'internal',
  'all',
] as const
export type TrafficClass = (typeof TRAFFIC_CLASS)[number]

/** composition output, from the OpenAPI document. */
export const COMPOSITION_OUTPUT = [
  'model',
  'html',
  'svg',
  'png',
  'print',
] as const
export type CompositionOutput = (typeof COMPOSITION_OUTPUT)[number]

/** html presentation, from the OpenAPI document. */
export const HTML_PRESENTATION = [
  'semantic',
  'visual',
] as const
export type HtmlPresentation = (typeof HTML_PRESENTATION)[number]

/** pattern scope, from the OpenAPI document. */
export const PATTERN_SCOPE = [
  'document',
  'node',
] as const
export type PatternScope = (typeof PATTERN_SCOPE)[number]

/** pattern status, from the OpenAPI document. */
export const PATTERN_STATUS = [
  'experimental',
  'stable',
  'deprecated',
] as const
export type PatternStatus = (typeof PATTERN_STATUS)[number]

/** pattern category, from the OpenAPI document. */
export const PATTERN_CATEGORY = [
  'document',
  'metrics',
  'stats',
  'process',
  'comparison',
  'timeline',
  'structure',
  'data',
  'faq',
  'code',
  'pricing',
  'gallery',
  'table',
  'dashboard',
  'application',
] as const
export type PatternCategory = (typeof PATTERN_CATEGORY)[number]

/** publishing guide kind, from the OpenAPI document. */
export const PUBLISHING_GUIDE_KIND = [
  'report',
  'diagram',
  'code',
] as const
export type PublishingGuideKind = (typeof PUBLISHING_GUIDE_KIND)[number]

/**
 * Every scope a credential can hold. `authorize()` has no hierarchy, so this
 * is a flat set and `*` is deliberately absent — it exists in stored grants,
 * never as something a form may hand out.
 */
export const PRODUCT_SCOPES = [
  'content:read',
  'content:write',
  'deck:render',
  'release:preview',
  'release:write',
  'site:admin',
  'access:admin',
  'webhook:admin',
  'api-key:admin',
  'identity:admin',
  'moderation:write',
  'audit:read',
  'stats:read',
] as const
export type ProductScope = (typeof PRODUCT_SCOPES)[number]

/**
 * The only custom properties settings.theme.tokens may name. An unknown key
 * fails the whole PATCH, which is why the console offers a menu of these and
 * never a free-text key.
 */
export const THEME_TOKENS = [
  'background',
  'foreground',
  'muted',
  'muted_foreground',
  'border',
  'primary',
  'primary_foreground',
  'chart_1',
  'chart_2',
  'chart_3',
  'chart_4',
  'chart_5',
  'radius',
  'font_family',
] as const
export type ThemeToken = (typeof THEME_TOKENS)[number]

/** Every event contentkit emits. An endpoint filter naming anything else is a 422. */
export const WEBHOOK_EVENT_TYPES = [
  'contentkit.contact.submitted',
  'contentkit.comment.submitted',
  'contentkit.comment.approved',
  'contentkit.content.published',
  'contentkit.content.unpublished',
  'contentkit.deck.published',
  'contentkit.release.published',
  'contentkit.release.failed',
  'contentkit.deck.release_failed',
] as const
export type WebhookEventType = (typeof WEBHOOK_EVENT_TYPES)[number]
