import test, { describe } from 'node:test'
import assert from 'node:assert/strict'
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { serveCockpit } from '../../src/cockpit.mjs'

// A fixture rather than the real build output: assets/cockpit is generated by
// scripts/build-cockpit.sh and is not in the repo, so a test that needed it
// would fail on a clean checkout for the wrong reason. build-binary.sh guards
// the real artefact instead.
function fixture() {
  const dir = mkdtempSync(join(tmpdir(), 'ck-cockpit-'))
  mkdirSync(join(dir, 'assets'))
  writeFileSync(join(dir, 'index.html'), '<!doctype html><title>ContentKit Cockpit</title>')
  writeFileSync(join(dir, 'assets', 'index-abc123.js'), 'console.log(1)')
  return dir
}

function request(path, { method = 'GET', headers = {}, dir } = {}) {
  const captured = { status: 0, headers: {}, body: '' }
  const res = {
    writeHead(status, responseHeaders = {}) {
      captured.status = status
      captured.headers = Object.fromEntries(
        Object.entries(responseHeaders).map(([key, value]) => [key.toLowerCase(), value]),
      )
      return res
    },
    end(body = '') {
      captured.body = String(body)
    },
  }
  const handled = serveCockpit({ method, headers }, res, path, dir)
  return { handled, ...captured }
}

describe('ContentKit Cockpit static serving', () => {
  const dir = fixture()

  test('unrelated paths are left to the rest of the router', () => {
    for (const path of ['/v1/sites', '/cockpitfoo', '/', '/health']) {
      assert.equal(request(path, { dir }).handled, false, `${path} must not be captured`)
    }
  })

  test('the shell answers on the prefix and on every client-side route', () => {
    for (const path of ['/cockpit', '/cockpit/', '/cockpit/releases', '/cockpit/sites/deep/link']) {
      const response = request(path, { dir })
      assert.equal(response.status, 200, path)
      assert.match(response.headers['content-type'], /text\/html/)
      // index.html is the one unfingerprinted file, so it must never be cached.
      assert.equal(response.headers['cache-control'], 'no-cache')
      assert.match(response.body, /ContentKit Cockpit/)
    }
  })

  test('fingerprinted assets are immutable and typed', () => {
    const response = request('/cockpit/assets/index-abc123.js', { dir })
    assert.equal(response.status, 200)
    assert.match(response.headers['content-type'], /application\/javascript/)
    assert.equal(response.headers['cache-control'], 'public,max-age=31536000,immutable')
  })

  test('a matching ETag revalidates instead of resending', () => {
    const first = request('/cockpit/', { dir })
    assert.ok(first.headers.etag)
    const second = request('/cockpit/', { dir, headers: { 'if-none-match': first.headers.etag } })
    assert.equal(second.status, 304)
    assert.equal(second.body, '')
  })

  test('dot segments cannot escape the bundle directory', () => {
    // The router hands over a normalized pathname, but the guard must hold on
    // its own: serving package.json or a private key from here would be fatal.
    for (const path of [
      '/cockpit/../package.json',
      '/cockpit/../../../etc/passwd',
      '/cockpit/assets/../../server.mjs',
    ]) {
      const response = request(path, { dir })
      assert.equal(response.status, 200, path)
      // Falls back to the shell rather than leaking anything above the root.
      assert.match(response.body, /ContentKit Cockpit/)
    }
  })

  test('writes are refused outright', () => {
    const response = request('/cockpit/', { method: 'POST', dir })
    assert.equal(response.status, 405)
    assert.equal(response.headers.allow, 'GET, HEAD')
  })

  test('HEAD answers with headers and no body', () => {
    const response = request('/cockpit/', { method: 'HEAD', dir })
    assert.equal(response.status, 200)
    assert.equal(response.body, '')
  })

  test('the console carries a first-party-only CSP and cannot be framed', () => {
    const { headers } = request('/cockpit/', { dir })
    assert.match(headers['content-security-policy'], /default-src 'self'/)
    assert.match(headers['content-security-policy'], /frame-ancestors 'none'/)
    assert.match(headers['content-security-policy'], /connect-src 'self'/)
    assert.equal(headers['x-frame-options'], 'DENY')
  })

  test('a deployment built without the console says so instead of 404ing', () => {
    const response = request('/cockpit/', { dir: join(tmpdir(), 'ck-cockpit-absent') })
    assert.equal(response.status, 503)
    assert.match(response.body, /not built/)
  })
})
