import test, { describe } from 'node:test'
import assert from 'node:assert/strict'
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { serveCockpit } from '../../src/cockpit.mjs'

const root = dirname(dirname(dirname(fileURLToPath(import.meta.url))))

// A fixture rather than the real build output: assets/cockpit is generated by
// scripts/build-cockpit.sh and is not in the repo, so a test that needed it
// would fail on a clean checkout for the wrong reason. build-binary.sh guards
// the real artefact instead.
function fixture() {
  const dir = mkdtempSync(join(tmpdir(), 'ck-cockpit-'))
  mkdirSync(join(dir, 'assets'))
  writeFileSync(join(dir, 'index.html'), '<!doctype html><title>ContentKit Cockpit</title>')
  writeFileSync(join(dir, 'assets', 'index-abc123.js'), 'console.log(1)')
  return dir
}

function request(path, { method = 'GET', headers = {}, dir } = {}) {
  const captured = { status: 0, headers: {}, body: '' }
  const res = {
    writeHead(status, responseHeaders = {}) {
      captured.status = status
      captured.headers = Object.fromEntries(
        Object.entries(responseHeaders).map(([key, value]) => [key.toLowerCase(), value]),
      )
      return res
    },
    end(body = '') {
      captured.body = String(body)
    },
  }
  const handled = serveCockpit({ method, headers }, res, path, dir)
  return { handled, ...captured }
}

describe('ContentKit Cockpit static serving', () => {
  const dir = fixture()

  test('unrelated paths are left to the rest of the router', () => {
    for (const path of ['/v1/sites', '/cockpitfoo', '/', '/health']) {
      assert.equal(request(path, { dir }).handled, false, `${path} must not be captured`)
    }
  })

  test('the shell answers on the prefix and on every client-side route', () => {
    for (const path of ['/cockpit', '/cockpit/', '/cockpit/releases', '/cockpit/sites/deep/link']) {
      const response = request(path, { dir })
      assert.equal(response.status, 200, path)
      assert.match(response.headers['content-type'], /text\/html/)
      // index.html is the one unfingerprinted file, so it must never be cached.
      assert.equal(response.headers['cache-control'], 'no-cache')
      assert.match(response.body, /ContentKit Cockpit/)
    }
  })

  test('fingerprinted assets are immutable and typed', () => {
    const response = request('/cockpit/assets/index-abc123.js', { dir })
    assert.equal(response.status, 200)
    assert.match(response.headers['content-type'], /application\/javascript/)
    assert.equal(response.headers['cache-control'], 'public,max-age=31536000,immutable')
  })

  test('a matching ETag revalidates instead of resending', () => {
    const first = request('/cockpit/', { dir })
    assert.ok(first.headers.etag)
    const second = request('/cockpit/', { dir, headers: { 'if-none-match': first.headers.etag } })
    assert.equal(second.status, 304)
    assert.equal(second.body, '')
  })

  test('dot segments cannot escape the bundle directory', () => {
    // The router hands over a normalized pathname, but the guard must hold on
    // its own: serving package.json or a private key from here would be fatal.
    for (const path of [
      '/cockpit/../package.json',
      '/cockpit/../../../etc/passwd',
      '/cockpit/assets/../../server.mjs',
    ]) {
      const response = request(path, { dir })
      assert.equal(response.status, 200, path)
      // Falls back to the shell rather than leaking anything above the root.
      assert.match(response.body, /ContentKit Cockpit/)
    }
  })

  test('writes are refused outright', () => {
    const response = request('/cockpit/', { method: 'POST', dir })
    assert.equal(response.status, 405)
    assert.equal(response.headers.allow, 'GET, HEAD')
  })

  test('HEAD answers with headers and no body', () => {
    const response = request('/cockpit/', { method: 'HEAD', dir })
    assert.equal(response.status, 200)
    assert.equal(response.body, '')
  })

  test('the console carries a first-party-only CSP and cannot be framed', () => {
    const { headers } = request('/cockpit/', { dir })
    assert.match(headers['content-security-policy'], /default-src 'self'/)
    assert.match(headers['content-security-policy'], /frame-ancestors 'none'/)
    assert.match(headers['content-security-policy'], /connect-src 'self'/)
    assert.equal(headers['x-frame-options'], 'DENY')
  })

  test('a deployment built without the console says so instead of 404ing', () => {
    const response = request('/cockpit/', { dir: join(tmpdir(), 'ck-cockpit-absent') })
    assert.equal(response.status, 503)
    assert.match(response.body, /not built/)
  })
})

// Regression: the Cockpit's sign-in and session are served by the OAuth mount,
// but src/server.mjs dispatches to that mount from an explicit allowlist. Both
// routes were absent from it, so they answered 404 in production while the
// mount itself was perfectly correct — which is exactly why this test drives
// the assembled app instead of the mount.
describe('Cockpit auth routes are reachable through the assembled app', () => {
  async function withApp(config, run) {
    const { createApp } = await import('../../src/server.mjs')
    const app = createApp(
      {
        publicUrl: 'http://127.0.0.1',
        version: 'test',
        trustProxy: false,
        maxBodyBytes: 1024,
        oauthSecret: 'secret',
        oauthProviders: [{ protocol: 'api_key', id: 'api-key', label: 'ContentKit API key' }],
        ...config,
      },
      {
        logger: { info() {}, warn() {}, error() {}, debug() {} },
        database: {
          db: {
            async query() {
              return []
            },
            async select() {
              return []
            },
            async insert() {
              return [{}]
            },
            async update() {
              return [{}]
            },
          },
          async close() {},
        },
        storage: {},
        repo: {},
        releases: { inflight: () => 0 },
        auth: {
          async authenticate() {
            return null
          },
          authorize: () => false,
        },
        outbox: { start() {}, stop() {} },
      },
    )
    await new Promise((resolve) => app.server.listen(0, '127.0.0.1', resolve))
    try {
      await run((path, init) => fetch(`http://127.0.0.1:${app.server.address().port}${path}`, init))
    } finally {
      app.limiter.stop()
      app.loginLimiter.stop()
      app.deckJobs.stop()
      await new Promise((resolve) => app.server.close(resolve))
    }
  }

  test('sign-in renders and the session reports "not signed in", never 404', async () => {
    await withApp({}, async (request) => {
      const login = await request('/v1/identity/cockpit-login?return_to=/cockpit/', { redirect: 'manual' })
      assert.notEqual(login.status, 404, 'the sign-in funnel must be dispatched to the OAuth mount')
      assert.ok([200, 302].includes(login.status), `unexpected status ${login.status}`)

      const session = await request('/v1/identity/session')
      // 401 is the console's cue to sign in; 404 would make it show an error.
      assert.equal(session.status, 401)
    })
  })

  test('turning MCP off must not lock operators out of their own console', async () => {
    await withApp({ mcpEnabled: false }, async (request) => {
      const login = await request('/v1/identity/cockpit-login', { redirect: 'manual' })
      assert.notEqual(login.status, 404)
      assert.equal((await request('/v1/identity/session')).status, 401)
    })
  })
})

/**
 * The console renders published HTML with the site's own stylesheet, and the
 * site writes its typography as `.prose p`, `.prose code`, `.prose table` —
 * templates.mjs puts every document body inside `<div class="prose">`. Scoping
 * turns those into `.ck-content .prose …`, a *descendant* selector, so a surface
 * that carries both classes on one element matches none of them and renders raw.
 *
 * That is what happened, and nothing caught it: the console still compiled, the
 * HTML was still correct, and only the paragraph spacing and the list bullets
 * were gone. There is no test runner in apps/cockpit, so the invariant is
 * asserted where it can be — against the two files that have to agree.
 */
describe('the console’s content surface matches the published page', () => {
  const cockpit = join(root, 'apps', 'cockpit', 'src', 'content')

  test('the rendered fragment sits inside a .prose descendant of .ck-content', async () => {
    const component = await readFile(join(cockpit, 'ContentHtml.tsx'), 'utf8')
    const surface = component.indexOf("'ck-content'")
    const prose = component.indexOf('className="prose"')
    assert.ok(surface >= 0, 'the surface element must still carry ck-content')
    assert.ok(prose > surface, 'the body must be a .prose element nested inside .ck-content')
    assert.match(
      component.slice(prose),
      /dangerouslySetInnerHTML/,
      'the HTML must be inserted into the .prose element, not beside it',
    )
  })

  test('every scoped prose rule is reachable from that structure', async () => {
    const css = await readFile(join(cockpit, 'site.scoped.css'), 'utf8')
    // `.container.prose` is deliberately unreachable: it sizes a page column
    // against the viewport, and the console's panes size themselves.
    const selectors = [...css.matchAll(/\.ck-content \.prose(?![-.\w])/g)]
    assert.ok(selectors.length > 5, `expected the site's prose typography to be scoped, found ${selectors.length}`)
  })
})
